apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: dummyapp
  name: 'dummyapp.fahadahammed.com'
spec:
  secretName: 'dummyapp.fahadahammed.com.cert'
  subject:
    organizations:
      - DummyApp
  dnsNames:
  - 'dummyapp.fahadahammed.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer