apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: dummyapp-development
  name: dummyapp-development.fahadahammed.com
  labels:
    app.kubernetes.io/name: dummyapp
    environment: development
spec:
#  selector:
#    matchLabels:
#      app.kubernetes.io/name: dummyapp
  secretName: dummyapp-development.fahadahammed.com
  subject:
    organizations:
      - DummyApp
  dnsNames:
  - dummyapp-development.fahadahammed.com
  
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
