name: Docker Image Build and Publish

on:
  release:
    types: [published]

env:
  VERSION: ${{github.ref_name}}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Container Image
      run: |
        VERSION=${{env.VERSION}} USERN=${{ secrets.DOCKERHUB_USERNAME }} make dockerBuild

    - name: Push the image to Dockerhub
      run: |
        VERSION=${{env.VERSION}} USERN=${{ secrets.DOCKERHUB_USERNAME }} make dockerPush
